### ISSUE TITLE
Where is Lectures.txt?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mitlm/mitlm#47]
```
I'm trying to follow the tutorial at 
https://code.google.com/p/mitlm/wiki/Tutorial, and want to make sure I'm doing 
it right. Where can I find the sample files like lectures.txt?
```

Original issue reported on code.google.com by `a.goodk...@gmail.com` on 14 Apr 2015 at 10:59

**Comment by giuliopaci** [comment]
I do not think that file is available. Probably Paul referenced a corpus he was using.

Anyway it is not difficult to create a corpus: just put one sentence per line in a text file. Tokens (words) must be space separated. Use line feed for line termination.
