### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by fbacker** [mitlm/mitlm#51]
Downloaded from git. run ./autogen.sh and ./configure. But when running sudo make install I get error. 

Running Ubuntu 14.04 LTS

	kidkic@ubuntu:~/mitlm$ sudo make install
	make[1]: Entering directory `/home/kidkic/mitlm'
	depbase=`echo src/util/CommandOptions.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
		/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"MIT\ Language\ Modeling\ Toolkit\" -DPACKAGE_TARNAME=\"mitlm\" -DPACKAGE_VERSION=\"0.4.1\" -DPACKAGE_STRING=\"MIT\ Language\ Modeling\ Toolkit\ 0.4.1\" -DPACKAGE_BUGREPORT=\"mitlm-dev@googlegroups.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"mitlm\" -DVERSION=\"0.4.1\" -DF77_FUNC\(name,NAME\)=name\ ##\ _ -DF77_FUNC_\(name,NAME\)=name\ ##\ _ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_STRING_H=1 -DHAVE_MATH_H=1 -DSTDC_HEADERS=1 -DHAVE___BUILTIN_CLZL=1 -I.  -I./src   -g -O2 -MT src/util/CommandOptions.lo -MD -MP -MF $depbase.Tpo -c -o src/util/CommandOptions.lo src/util/CommandOptions.cpp &&\
		mv -f $depbase.Tpo $depbase.Plo
	libtool: compile:  g++ "-DPACKAGE_NAME=\"MIT Language Modeling Toolkit\"" -DPACKAGE_TARNAME=\"mitlm\" -DPACKAGE_VERSION=\"0.4.1\" "-DPACKAGE_STRING=\"MIT Language Modeling Toolkit 0.4.1\"" -DPACKAGE_BUGREPORT=\"mitlm-dev@googlegroups.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"mitlm\" -DVERSION=\"0.4.1\" "-DF77_FUNC(name,NAME)=name ## _" "-DF77_FUNC_(name,NAME)=name ## _" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_STRING_H=1 -DHAVE_MATH_H=1 -DSTDC_HEADERS=1 -DHAVE___BUILTIN_CLZL=1 -I. -I./src -g -O2 -MT src/util/CommandOptions.lo -MD -MP -MF src/util/.deps/CommandOptions.Tpo -c src/util/CommandOptions.cpp  -fPIC -DPIC -o src/util/.libs/CommandOptions.o
	In file included from /usr/include/c++/4.8/unordered_map:35:0,
	                 from src/util/CommandOptions.h:45,
	                 from src/util/CommandOptions.cpp:39:
	/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
	 #error This file requires compiler and library support for the \
	  ^
	In file included from src/util/CommandOptions.cpp:39:0:
	src/util/CommandOptions.h:46:12: error: 'std::unordered_map' has not been declared
	 using std::unordered_map;
	            ^
	src/util/CommandOptions.h:65:13: error: 'unordered_map' does not name a type
	     typedef unordered_map<string, int>::const_iterator hash_map_iter;
	             ^
	src/util/CommandOptions.h:71:5: error: 'unordered_map' does not name a type
	     unordered_map<string, int> _nameIndexMap;
	     ^
	src/util/CommandOptions.cpp: In member function 'void mitlm::CommandOptions::AddOption(const char*, const char*, const char*, const char*)':
	src/util/CommandOptions.cpp:59:9: error: '_nameIndexMap' was not declared in this scope
	         _nameIndexMap[names[i]] = _options.size();
	         ^
	src/util/CommandOptions.cpp: In member function 'bool mitlm::CommandOptions::ParseArguments(int, const char**)':
	src/util/CommandOptions.cpp:74:9: error: 'hash_map_iter' was not declared in this scope
	         hash_map_iter iter = _nameIndexMap.find(&argName[1]);
	         ^
	src/util/CommandOptions.cpp:74:23: error: expected ';' before 'iter'
	         hash_map_iter iter = _nameIndexMap.find(&argName[1]);
	                       ^
	src/util/CommandOptions.cpp:75:13: error: 'iter' was not declared in this scope
	         if (iter == _nameIndexMap.end()) {
	             ^
	src/util/CommandOptions.cpp:75:21: error: '_nameIndexMap' was not declared in this scope
	         if (iter == _nameIndexMap.end()) {
	                     ^
	src/util/CommandOptions.cpp:79:21: error: 'iter' was not declared in this scope
	         if (_values[iter->second] != NULL) {
	                     ^
	src/util/CommandOptions.cpp:86:17: error: 'iter' was not declared in this scope
	         _values[iter->second] = value;
	                 ^
	src/util/CommandOptions.cpp: In member function 'const char* mitlm::CommandOptions::operator[](const char*) const':
	src/util/CommandOptions.cpp:121:5: error: 'hash_map_iter' was not declared in this scope
	     hash_map_iter iter = _nameIndexMap.find(name);
	     ^
	src/util/CommandOptions.cpp:121:19: error: expected ';' before 'iter'
	     hash_map_iter iter = _nameIndexMap.find(name);
	                   ^
	In file included from /usr/include/c++/4.8/cassert:43:0,
	                 from src/util/CommandOptions.cpp:36:
	src/util/CommandOptions.cpp:122:12: error: 'iter' was not declared in this scope
	     assert(iter != _nameIndexMap.end());
	            ^
	src/util/CommandOptions.cpp:122:20: error: '_nameIndexMap' was not declared in this scope
	     assert(iter != _nameIndexMap.end());
	                    ^
	make[1]: *** [src/util/CommandOptions.lo] Error 1
	make[1]: Leaving directory `/home/kidkic/mitlm'
	make: *** [install-recursive] Error 1

Checking gcc -v gives me **gcc version 4.8.5**

**Comment by giuliopaci** [comment]
Can you try to compile again using this line for the configure step:

`CXX="g++ -std=c++11" ./configure`

and then perform the usual

`make`

and

`sudo make install` ?

If understand correctly the compiler messages, this should solve the issue.

BTW: I noticed that you mentioned `./autogen.sh`, `./configure` and `sudo make install`.
I recommend to add `make` step after `./configure` and, if possible, avoid running `sudo` or anything as root, unless you previously personally investigated that the package is safe.
`./configure --prefix=<absolute_installation_path_prefix>` will let you completely avoid root permissions.

**Comment by fbacker** [comment]
Thanks for the help. Now it worked perfectly :)

Also thx for the input, still learning linux terminals and how to 'think'.
