### ISSUE TITLE
mitlm build error

### ISSUE THREAD

**Issue by mosherayman** [mitlm/mitlm#52]
I run the ./autogen.sh script and i get the following errors:

./configure: line 19642: AX_CXX_HEADER_TR1_UNORDERED_MAP: command not found
./configure: line 19643: syntax error near unexpected token `noext,'
./configure: line 19643: `AX_CXX_COMPILE_STDCXX_11(noext, optional)'

i got this on multiple linux paltforms

thanks

**Comment by giuliopaci** [comment]
You need the autoconf archive macros in order to use autogen.sh.
If you are using Debian (or a derivative, like Ubuntu), install the autoconf-archive package and try again. On other distributions the package name should be similar.

**Comment by mosherayman** [comment]
thanks
