### ISSUE TITLE
can't be installed mitlm 0.4.1

### ISSUE THREAD

**Issue by kaierlong** [mitlm/mitlm#55]
when I ren atuogen.sh and ./configure,there were some errors like:
./configure: line 20051: AX_CXX_HEADER_UNORDERED_MAP: command not found
./configure: line 20052: syntax error near unexpected token `noext,'
./configure: line 20052: `AX_CXX_COMPILE_STDCXX_11(noext, optional)'

can anyone help how to deal with this?

**Comment by giuliopaci** [comment]
You are missing autoconf-archive, that contains the two missing macros. Install it and everything should work.

**Comment by kaierlong** [comment]
thanks, I changed another version and it worked well.
