### ISSUE TITLE
compile fails on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by mdeisher** [mitlm/mitlm#56]
autogen is not properly configuring compiler flags.  So make fails with an error from /usr/include/c++/4.8/bits/c++0x_warning.h.

It would be nice if autogen did the right thing.  But we can work around it by re-running configure with:

./configure CFLAGS='-g -O2 -std=c++11' CXXFLAGS='-g -O2 -std=c++11'

**Comment by giuliopaci** [comment]
This should be fixed now.
I am closing the issue.
