### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by yetcome** [mitlm/mitlm#62]
./configure: line 19641: AX_CXX_HEADER_TR1_UNORDERED_MAP: command not found
./configure: line 19642: syntax error near unexpected token `noext,'
./configure: line 19642: `AX_CXX_COMPILE_STDCXX_11(noext, optiona

**Comment by giuliopaci** [comment]
You need to install autoconf-archive and rerun autogen.sh or autoreconf.

**Comment by zerzavot** [comment]
For installation on ubuntu:20.04 you need to install some dependencies:

```
sudo apt-get install autotools-dev 
sudo apt-get install automake 
sudo apt-get install autoconf 
sudo apt-get install libtool 
sudo apt install build-essential 
sudo apt-get install manpages-dev  
sudo apt-get install -y autoconf-archive
sudo apt-get install gfortran 
```

Then complete the following steps:.
```
./autogen.sh 
make 
make install 
```
Now, you can use MITLM for creating a model :)

Eg.  `estimate-ngram -text /home/user/text.txt -write-lm my_model.lm`
