### ISSUE TITLE
Error when make.

### ISSUE THREAD

**Issue by enjoysport2022** [mitlm/mitlm#67]
Hi, I'm trying to compile but i'm getting the following error:

step 1.  $sh autogen.sh
step 2.  $make

libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.

Thx very much.

**Comment by giuliopaci** [comment]
How did you get the source code?

These symptoms happen when you try to regenerate the build files (i.e., you run autogen.sh) after an upgrade of libtool.
It may happen because either downloaded a tarball or because you are recompiling the tool after a long time.

In both cases you can try to run `autoreconf -is`, which is a modern, recommended alternative to autogen.sh. If you still have the same issue, just delete aclocal.m4 and build-aux directory and try again.

If the above instructions work for you, please close this issue.

**Comment by enjoysport2022** [comment]
Hi, Paci, thx for your help.

I get the source code with the operation "git clone https://github.com/mitlm/mitlm.git";

Now I try run "autoreconf -is", got the following warming:

libtoolize: You should add the contents of the following files to 'aclocal.m4':
libtoolize:   '/home/user/anaconda3/share/aclocal/libtool.m4'
libtoolize:   '/home/user/anaconda3/share/aclocal/ltoptions.m4'
libtoolize:   '/home/user/anaconda3/share/aclocal/ltversion.m4'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.

I fellow your guide, delete the aclocal.m4 and build-aux directory, and do:
1. autoreconf -is
2. ./configure
3. make

still get the error:

libtool: Version mismatch error. This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.

**Comment by giuliopaci** [comment]
Hi,
  I just had a look at https://stackoverflow.com/questions/3096989/libtool-version-mismatch-error

And then re-read your last message. It seems that you have more than one libtool installed, one from your system and one from anaconda (same as https://stackoverflow.com/questions/3096989/libtool-version-mismatch-error#comment79630583_9800951), causing the issue as the system is probably mixing files and tools from the two different installations.
I think the easiest solution is to remove one of the conflicting versions.

**Comment by giuliopaci** [comment]
I am closing the issue since I did not receive any feedback since a long time.
