### ISSUE TITLE
Is there any document to introduce how to use the tools?

### ISSUE THREAD

**Issue by gzhcv** [mitlm/mitlm#69]
Hi, i am new to language model.  i could not find any document about the MITLM,  any help?

**Comment by giuliopaci** [comment]
Unfortunately the wiki pages on Google code are not accessible anymore.
They have been exported to GitHub, but are still a little bit hidden, as they are in the wiki branch of this repository:

https://github.com/mitlm/mitlm/tree/wiki

You can start from here:
https://github.com/mitlm/mitlm/blob/wiki/Tutorial.md
