### ISSUE TITLE
./configure: line 19641: AX_CXX_HEADER_TR1_UNORDERED_MAP: command not found

### ISSUE THREAD

**Issue by Balezemaldo** [mitlm/mitlm#76]
./configure: line 19641: AX_CXX_HEADER_TR1_UNORDERED_MAP: command not found
./configure: line 19642: syntax error near unexpected token `noext,'
./configure: line 19642: `AX_CXX_COMPILE_STDCXX_11(noext, optional)'

**Comment by danijel3** [comment]
`apt install autoconf-archive`
